# github setting
safe: true
# source: <your pages repo>
# destination: <the build dir>
lsi: false
# pygments: true
markdown: kramdown
kramdown:
  input: GFM

# my setting
author:
  name: ongaeshi
  email: ongaeshi0621@gmail.com

locales:
  sitelinks:
    en:
      - text: Home
        url:  /en
      # - text: Downloads
      #   url:  /en
      # - text: Documentation
      #   url:  /en
    ja:
      - text: ホーム
        url:  /ja
      - text: ダウンロード
        url:  /ja/download.html
      - text: ドキュメント
        url:  /ja/doc
      - text: ライブラリ
        url:  /ja/lib.html

  footerlinks:
    - text: English
      url:  /en
    - text: 日本語
      url:  /ja
